In [1]:
import pandas as pd

df = pd.read_csv("zomato.csv")

df.head()

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
0,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari
2,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",San Churro Cafe,Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari
3,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",Addhuri Udupi Bhojana,No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari
4,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",Grand Village,No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51717 entries, 0 to 51716
Data columns (total 17 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   url                          51717 non-null  object
 1   address                      51717 non-null  object
 2   name                         51717 non-null  object
 3   online_order                 51717 non-null  object
 4   book_table                   51717 non-null  object
 5   rate                         43942 non-null  object
 6   votes                        51717 non-null  int64
 7   phone                        50509 non-null  object
 8   location                     51696 non-null  object
 9   rest_type                    51490 non-null  object
 10  dish_liked                   23639 non-null  object
 11  cuisines                     51672 non-null  object
 12  approx_cost(for two people)  51371 non-null  object
 13  reviews_list                 51717 non-null  object
 14  menu_item                    51717 non-null  object
 15  listed_in(type)              51717 non-null  object
 16  listed_in(city)              51717 non-null  object
dtypes: int64(1), object(16)
memory usage: 6.7+ MB

In [3]:
# checking missing values 

df.isnull().sum()

url                                0
address                            0
name                               0
online_order                       0
book_table                         0
rate                            7775
votes                              0
phone                           1208
location                          21
rest_type                        227
dish_liked                     28078
cuisines                          45
approx_cost(for two people)      346
reviews_list                       0
menu_item                          0
listed_in(type)                    0
listed_in(city)                    0
dtype: int64

In [4]:
# drop unnecessary columns from dataset 

df = df.drop(['url', 'address', 'phone', 'reviews_list','menu_item'], axis=1)

df.head()

,name,online_order,book_table,rate,votes,location,rest_type,dish_liked,cuisines,approx_cost(for two people),listed_in(type),listed_in(city)
0,Jalsa,Yes,Yes,4.1/5,775,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,Buffet,Banashankari
1,Spice Elephant,Yes,No,4.1/5,787,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,Buffet,Banashankari
2,San Churro Cafe,Yes,No,3.8/5,918,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,Buffet,Banashankari
3,Addhuri Udupi Bhojana,No,No,3.7/5,88,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,Buffet,Banashankari
4,Grand Village,No,No,3.8/5,166,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,Buffet,Banashankari

In [5]:
# clean rate columns 

df['rate'] = df['rate'].str.replace('/5',' ')
df['rate'] = df['rate'].replace(['NEW','-'],None)
df['rate'] = df['rate'].astype(float)

df['rate'].head()

0    4.1
1    4.1
2    3.8
3    3.7
4    3.8
Name: rate, dtype: float64

In [6]:
# clean approx_cost

df['approx_cost(for two people)'] = df['approx_cost(for two people)'].str.replace(',','')
df['approx_cost(for two people)'] = df['approx_cost(for two people)'].astype(float)

In [7]:
df['approx_cost(for two people)'].head()

0    800.0
1    800.0
2    800.0
3    300.0
4    600.0
Name: approx_cost(for two people), dtype: float64

In [8]:
# handle dish_liked 
# filling null values with not mentioned

df['dish_liked'] = df['dish_liked'].fillna("Not Mentioned")

In [9]:
df.isnull().sum()

name                               0
online_order                       0
book_table                         0
rate                           10052
votes                              0
location                          21
rest_type                        227
dish_liked                         0
cuisines                          45
approx_cost(for two people)      346
listed_in(type)                    0
listed_in(city)                    0
dtype: int64

In [10]:
df = df.dropna(subset=['rate'])
df = df.dropna()

In [11]:
df.isnull().sum()

name                           0
online_order                   0
book_table                     0
rate                           0
votes                          0
location                       0
rest_type                      0
dish_liked                     0
cuisines                       0
approx_cost(for two people)    0
listed_in(type)                0
listed_in(city)                0
dtype: int64

In [12]:
df.shape

(41263, 12)

# Basic Overview Analysis

In [13]:
# 1. Average Rating 

df['rate'].mean()

np.float64(3.702011487288854)

In [14]:
# 2) Average cost for two 

df['approx_cost(for two people)'].mean()

np.float64(603.9140634466713)

In [15]:
# top 10  locations by restaurants count
 
df['location'].value_counts().head(10)

location
BTM                      3879
Koramangala 5th Block    2297
HSR                      1993
Indiranagar              1800
JP Nagar                 1710
Jayanagar                1634
Whitefield               1568
Marathahalli             1410
Bannerghatta Road        1226
Koramangala 7th Block    1055
Name: count, dtype: int64

In [16]:
# top rated locations

df.groupby('location')['rate'].mean().round(2).sort_values(ascending=False).head(10)

location
Lavelle Road             4.14
Koramangala 3rd Block    4.02
St. Marks Road           4.02
Koramangala 5th Block    4.01
Church Street            3.99
Sankey Road              3.97
Koramangala 4th Block    3.92
Cunningham Road          3.90
Residency Road           3.86
Koramangala 7th Block    3.85
Name: rate, dtype: float64

# Feature Engineering

In [17]:
# creste cost category 

def cost_category(x):
    if x <=300:
        return"Budget"
    elif x <= 700:
        return "Mid Range"
    else:
        return "premium"
    
df['cost_category'] = df['approx_cost(for two people)'].apply(cost_category)

In [18]:
df['cost_category'].value_counts()

cost_category
Mid Range    18381
Budget       12535
premium      10347
Name: count, dtype: int64

In [19]:
# online order impact 

df.groupby('online_order')['rate'].mean().round(2)

online_order
No     3.66
Yes    3.72
Name: rate, dtype: float64

In [20]:
# save file 

df.to_csv("zomato_analysis.ipynb",index = False)

In [21]:
df.duplicated().sum()

np.int64(73)

In [22]:
df = df.drop_duplicates()

In [23]:
df.duplicated().sum()

np.int64(0)

In [24]:
df.shape

(41190, 13)

In [25]:
df.describe()

               rate         votes  approx_cost(for two people)
count  41190.000000  41190.000000                 41190.000000
mean       3.701731    352.066715                   603.545909
std        0.439929    883.461453                   464.651174
min        1.800000      0.000000                    40.000000
25%        3.400000     21.000000                   300.000000
50%        3.700000     73.000000                   500.000000
75%        4.000000    277.000000                   750.000000
max        4.900000  16832.000000                  6000.000000

In [26]:
df = df[(df['rate'] >= 1) & (df['rate'] <= 5)]

In [27]:
df.describe().round(2)

           rate     votes  approx_cost(for two people)
count  41190.00  41190.00                     41190.00
mean       3.70    352.07                       603.55
std        0.44    883.46                       464.65
min        1.80      0.00                        40.00
25%        3.40     21.00                       300.00
50%        3.70     73.00                       500.00
75%        4.00    277.00                       750.00
max        4.90  16832.00                      6000.00

In [28]:
# corrleation check 

df[['rate','votes','approx_cost(for two people)']].corr().round(2)

                             rate  votes  approx_cost(for two people)
rate                         1.00   0.43                         0.38
votes                        0.43   1.00                         0.37
approx_cost(for two people)  0.38   0.37                         1.00

In [29]:
# top location analysis

df.groupby('location')['rate'].mean().round(2).sort_values(ascending=False).head(10)

location
Lavelle Road             4.14
Koramangala 3rd Block    4.02
St. Marks Road           4.02
Koramangala 5th Block    4.01
Church Street            3.99
Sankey Road              3.97
Koramangala 4th Block    3.92
Cunningham Road          3.90
Residency Road           3.86
Koramangala 7th Block    3.85
Name: rate, dtype: float64

In [30]:
# online order impact

df.groupby('online_order')['rate'].mean().round(2)

online_order
No     3.66
Yes    3.72
Name: rate, dtype: float64

In [31]:
# save file 

df.to_csv("zomato_analysis.ipynb",index = False)

In [32]:
df.isnull().sum()

name                           0
online_order                   0
book_table                     0
rate                           0
votes                          0
location                       0
rest_type                      0
dish_liked                     0
cuisines                       0
approx_cost(for two people)    0
listed_in(type)                0
listed_in(city)                0
cost_category                  0
dtype: int64

In [33]:

df.to_csv("zomato_analysis.ipynb",index = False)

In [34]:
df.to_csv("zomato_cleaned.csv",index=False)

In [35]:
import os
os.getcwd()

'c:\\Users\\piyush\\OneDrive\\Desktop\\zomato project'

In [36]:
df.isnull().sum()

name                           0
online_order                   0
book_table                     0
rate                           0
votes                          0
location                       0
rest_type                      0
dish_liked                     0
cuisines                       0
approx_cost(for two people)    0
listed_in(type)                0
listed_in(city)                0
cost_category                  0
dtype: int64

In [37]:
# rename columns 

df.rename(columns={'approx_cost(for two people)': 'approx_cost_for_two',
                   'listed_in(type)': 'listed_in_type',
                   'listed_in(city)': 'listed_in_city'}, inplace=True)

In [38]:
df.columns

Index(['name', 'online_order', 'book_table', 'rate', 'votes', 'location',
       'rest_type', 'dish_liked', 'cuisines', 'approx_cost_for_two',
       'listed_in_type', 'listed_in_city', 'cost_category'],
      dtype='object')

In [39]:
df.to_csv("zomato_cleaned_final.csv",index=False)